// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TranslationConfiguration translation configuration
//
// swagger:model TranslationConfiguration
type TranslationConfiguration struct {

	// auto
	// Required: true
	Auto *bool `json:"auto"`

	// use libra
	// Required: true
	UseLibra *bool `json:"use_libra"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *TranslationConfiguration) UnmarshalJSON(data []byte) error {
	var props struct {

		// auto
		// Required: true
		Auto *bool `json:"auto"`

		// use libra
		// Required: true
		UseLibra *bool `json:"use_libra"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Auto = props.Auto
	m.UseLibra = props.UseLibra
	return nil
}

// Validate validates this translation configuration
func (m *TranslationConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuto(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUseLibra(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TranslationConfiguration) validateAuto(formats strfmt.Registry) error {

	if err := validate.Required("auto", "body", m.Auto); err != nil {
		return err
	}

	return nil
}

func (m *TranslationConfiguration) validateUseLibra(formats strfmt.Registry) error {

	if err := validate.Required("use_libra", "body", m.UseLibra); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this translation configuration based on context it is used
func (m *TranslationConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TranslationConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TranslationConfiguration) UnmarshalBinary(b []byte) error {
	var res TranslationConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
