// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Version version
//
// swagger:model Version
type Version struct {

	// lang name
	LangName string `json:"lang_name,omitempty"`

	// locale
	// Required: true
	Locale *string `json:"locale"`

	// localization id
	LocalizationID int64 `json:"localization_id,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// platform
	Platform int64 `json:"platform,omitempty"`

	// updated at
	// Required: true
	UpdatedAt *int64 `json:"updated_at"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *Version) UnmarshalJSON(data []byte) error {
	var props struct {

		// lang name
		LangName string `json:"lang_name,omitempty"`

		// locale
		// Required: true
		Locale *string `json:"locale"`

		// localization id
		LocalizationID int64 `json:"localization_id,omitempty"`

		// path
		Path string `json:"path,omitempty"`

		// platform
		Platform int64 `json:"platform,omitempty"`

		// updated at
		// Required: true
		UpdatedAt *int64 `json:"updated_at"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.LangName = props.LangName
	m.Locale = props.Locale
	m.LocalizationID = props.LocalizationID
	m.Path = props.Path
	m.Platform = props.Platform
	m.UpdatedAt = props.UpdatedAt
	return nil
}

// Validate validates this version
func (m *Version) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocale(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Version) validateLocale(formats strfmt.Registry) error {

	if err := validate.Required("locale", "body", m.Locale); err != nil {
		return err
	}

	return nil
}

func (m *Version) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updated_at", "body", m.UpdatedAt); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this version based on context it is used
func (m *Version) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Version) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Version) UnmarshalBinary(b []byte) error {
	var res Version
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
