// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: const.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserStatus int32

const (
	UserStatus_USER_ACTIVE     UserStatus = 0
	UserStatus_USER_NOT_ACTIVE UserStatus = 1
	UserStatus_USER_IS_BANNED  UserStatus = 2
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_ACTIVE",
		1: "USER_NOT_ACTIVE",
		2: "USER_IS_BANNED",
	}
	UserStatus_value = map[string]int32{
		"USER_ACTIVE":     0,
		"USER_NOT_ACTIVE": 1,
		"USER_IS_BANNED":  2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{0}
}

type UserRole int32

const (
	UserRole_USER_ROLE_ADMIN      UserRole = 0
	UserRole_USER_ROLE_TRANSLATOR UserRole = 1
	UserRole_USER_ROLE_MODERATOR  UserRole = 2
	UserRole_USER_ROLE_USER       UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_ADMIN",
		1: "USER_ROLE_TRANSLATOR",
		2: "USER_ROLE_MODERATOR",
		3: "USER_ROLE_USER",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_ADMIN":      0,
		"USER_ROLE_TRANSLATOR": 1,
		"USER_ROLE_MODERATOR":  2,
		"USER_ROLE_USER":       3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_ACTIVE     Status = 0
	Status_NOT_ACTIVE Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "ACTIVE",
		1: "NOT_ACTIVE",
	}
	Status_value = map[string]int32{
		"ACTIVE":     0,
		"NOT_ACTIVE": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{2}
}

type StorageType int32

const (
	StorageType_STORAGE_TYPE_LOCAL StorageType = 0
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "STORAGE_TYPE_LOCAL",
	}
	StorageType_value = map[string]int32{
		"STORAGE_TYPE_LOCAL": 0,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[3].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[3]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{3}
}

type TranslationStatus int32

const (
	TranslationStatus_TRANSLATION_ACTIVE TranslationStatus = 0
	TranslationStatus_TRANSLATION_EMPTY  TranslationStatus = 1
)

// Enum value maps for TranslationStatus.
var (
	TranslationStatus_name = map[int32]string{
		0: "TRANSLATION_ACTIVE",
		1: "TRANSLATION_EMPTY",
	}
	TranslationStatus_value = map[string]int32{
		"TRANSLATION_ACTIVE": 0,
		"TRANSLATION_EMPTY":  1,
	}
)

func (x TranslationStatus) Enum() *TranslationStatus {
	p := new(TranslationStatus)
	*p = x
	return p
}

func (x TranslationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranslationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[4].Descriptor()
}

func (TranslationStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[4]
}

func (x TranslationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranslationStatus.Descriptor instead.
func (TranslationStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{4}
}

type PlatformType int32

const (
	PlatformType_PLATFORM_TYPE_WEB     PlatformType = 0
	PlatformType_PLATFORM_TYPE_IOS     PlatformType = 1
	PlatformType_PLATFORM_TYPE_ANDROID PlatformType = 2
)

// Enum value maps for PlatformType.
var (
	PlatformType_name = map[int32]string{
		0: "PLATFORM_TYPE_WEB",
		1: "PLATFORM_TYPE_IOS",
		2: "PLATFORM_TYPE_ANDROID",
	}
	PlatformType_value = map[string]int32{
		"PLATFORM_TYPE_WEB":     0,
		"PLATFORM_TYPE_IOS":     1,
		"PLATFORM_TYPE_ANDROID": 2,
	}
)

func (x PlatformType) Enum() *PlatformType {
	p := new(PlatformType)
	*p = x
	return p
}

func (x PlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[5].Descriptor()
}

func (PlatformType) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[5]
}

func (x PlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformType.Descriptor instead.
func (PlatformType) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{5}
}

var File_const_proto protoreflect.FileDescriptor

var file_const_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x2a, 0x46, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x49,
	0x53, 0x5f, 0x42, 0x41, 0x4e, 0x4e, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x66, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52,
	0x4f, 0x4c, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x4c, 0x41,
	0x54, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x4f,
	0x4c, 0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x12,
	0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x10, 0x03, 0x2a, 0x24, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x54, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x25, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x4f, 0x52, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x2a,
	0x42, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x4c, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11,
	0x54, 0x52, 0x41, 0x4e, 0x53, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x4d, 0x50, 0x54,
	0x59, 0x10, 0x01, 0x2a, 0x57, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x45, 0x42, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4c,
	0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4f, 0x53, 0x10,
	0x01, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06,
	0x70, 0x62, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_const_proto_rawDescOnce sync.Once
	file_const_proto_rawDescData = file_const_proto_rawDesc
)

func file_const_proto_rawDescGZIP() []byte {
	file_const_proto_rawDescOnce.Do(func() {
		file_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_const_proto_rawDescData)
	})
	return file_const_proto_rawDescData
}

var file_const_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_const_proto_goTypes = []interface{}{
	(UserStatus)(0),        // 0: api.UserStatus
	(UserRole)(0),          // 1: api.UserRole
	(Status)(0),            // 2: api.Status
	(StorageType)(0),       // 3: api.StorageType
	(TranslationStatus)(0), // 4: api.TranslationStatus
	(PlatformType)(0),      // 5: api.PlatformType
}
var file_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_const_proto_init() }
func file_const_proto_init() {
	if File_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_const_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_const_proto_goTypes,
		DependencyIndexes: file_const_proto_depIdxs,
		EnumInfos:         file_const_proto_enumTypes,
	}.Build()
	File_const_proto = out.File
	file_const_proto_rawDesc = nil
	file_const_proto_goTypes = nil
	file_const_proto_depIdxs = nil
}
