// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: const.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserStatus int32

const (
	UserStatus_USER_ACTIVE     UserStatus = 0
	UserStatus_USER_NOT_ACTIVE UserStatus = 1
	UserStatus_USER_IS_BANNED  UserStatus = 2
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_ACTIVE",
		1: "USER_NOT_ACTIVE",
		2: "USER_IS_BANNED",
	}
	UserStatus_value = map[string]int32{
		"USER_ACTIVE":     0,
		"USER_NOT_ACTIVE": 1,
		"USER_IS_BANNED":  2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{0}
}

type UserRole int32

const (
	UserRole_USER_ROLE_ADMIN      UserRole = 0
	UserRole_USER_ROLE_TRANSLATOR UserRole = 1
	UserRole_USER_ROLE_MODERATOR  UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_ADMIN",
		1: "USER_ROLE_TRANSLATOR",
		2: "USER_ROLE_MODERATOR",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_ADMIN":      0,
		"USER_ROLE_TRANSLATOR": 1,
		"USER_ROLE_MODERATOR":  2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{1}
}

type IdentifierStatus int32

const (
	IdentifierStatus_IDENTIFIER_ACTIVE     IdentifierStatus = 0
	IdentifierStatus_IDENTIFIER_NOT_ACTIVE IdentifierStatus = 1
)

// Enum value maps for IdentifierStatus.
var (
	IdentifierStatus_name = map[int32]string{
		0: "IDENTIFIER_ACTIVE",
		1: "IDENTIFIER_NOT_ACTIVE",
	}
	IdentifierStatus_value = map[string]int32{
		"IDENTIFIER_ACTIVE":     0,
		"IDENTIFIER_NOT_ACTIVE": 1,
	}
)

func (x IdentifierStatus) Enum() *IdentifierStatus {
	p := new(IdentifierStatus)
	*p = x
	return p
}

func (x IdentifierStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentifierStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[2].Descriptor()
}

func (IdentifierStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[2]
}

func (x IdentifierStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentifierStatus.Descriptor instead.
func (IdentifierStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{2}
}

type LocalizationIdentifierStatus int32

const (
	LocalizationIdentifierStatus_LOCALIZATION_IDENTIFIER_ACTIVE     LocalizationIdentifierStatus = 0
	LocalizationIdentifierStatus_LOCALIZATION_IDENTIFIER_NOT_ACTIVE LocalizationIdentifierStatus = 1
)

// Enum value maps for LocalizationIdentifierStatus.
var (
	LocalizationIdentifierStatus_name = map[int32]string{
		0: "LOCALIZATION_IDENTIFIER_ACTIVE",
		1: "LOCALIZATION_IDENTIFIER_NOT_ACTIVE",
	}
	LocalizationIdentifierStatus_value = map[string]int32{
		"LOCALIZATION_IDENTIFIER_ACTIVE":     0,
		"LOCALIZATION_IDENTIFIER_NOT_ACTIVE": 1,
	}
)

func (x LocalizationIdentifierStatus) Enum() *LocalizationIdentifierStatus {
	p := new(LocalizationIdentifierStatus)
	*p = x
	return p
}

func (x LocalizationIdentifierStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalizationIdentifierStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[3].Descriptor()
}

func (LocalizationIdentifierStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[3]
}

func (x LocalizationIdentifierStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalizationIdentifierStatus.Descriptor instead.
func (LocalizationIdentifierStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{3}
}

type CategoryStatus int32

const (
	CategoryStatus_CATEGORY_ACTIVE     CategoryStatus = 0
	CategoryStatus_CATEGORY_NOT_ACTIVE CategoryStatus = 1
)

// Enum value maps for CategoryStatus.
var (
	CategoryStatus_name = map[int32]string{
		0: "CATEGORY_ACTIVE",
		1: "CATEGORY_NOT_ACTIVE",
	}
	CategoryStatus_value = map[string]int32{
		"CATEGORY_ACTIVE":     0,
		"CATEGORY_NOT_ACTIVE": 1,
	}
)

func (x CategoryStatus) Enum() *CategoryStatus {
	p := new(CategoryStatus)
	*p = x
	return p
}

func (x CategoryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[4].Descriptor()
}

func (CategoryStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[4]
}

func (x CategoryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoryStatus.Descriptor instead.
func (CategoryStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{4}
}

type LocalizationStatus int32

const (
	LocalizationStatus_LOCALIZATION_ACTIVE     LocalizationStatus = 0
	LocalizationStatus_LOCALIZATION_NOT_ACTIVE LocalizationStatus = 1
)

// Enum value maps for LocalizationStatus.
var (
	LocalizationStatus_name = map[int32]string{
		0: "LOCALIZATION_ACTIVE",
		1: "LOCALIZATION_NOT_ACTIVE",
	}
	LocalizationStatus_value = map[string]int32{
		"LOCALIZATION_ACTIVE":     0,
		"LOCALIZATION_NOT_ACTIVE": 1,
	}
)

func (x LocalizationStatus) Enum() *LocalizationStatus {
	p := new(LocalizationStatus)
	*p = x
	return p
}

func (x LocalizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[5].Descriptor()
}

func (LocalizationStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[5]
}

func (x LocalizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalizationStatus.Descriptor instead.
func (LocalizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{5}
}

type Status int32

const (
	Status_ACTIVE     Status = 0
	Status_NOT_ACTIVE Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "ACTIVE",
		1: "NOT_ACTIVE",
	}
	Status_value = map[string]int32{
		"ACTIVE":     0,
		"NOT_ACTIVE": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[6].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[6]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{6}
}

type TranslationStatus int32

const (
	TranslationStatus_TRANSLATION_ACTIVE TranslationStatus = 0
	TranslationStatus_TRANSLATION_HIDDEN TranslationStatus = 1
)

// Enum value maps for TranslationStatus.
var (
	TranslationStatus_name = map[int32]string{
		0: "TRANSLATION_ACTIVE",
		1: "TRANSLATION_HIDDEN",
	}
	TranslationStatus_value = map[string]int32{
		"TRANSLATION_ACTIVE": 0,
		"TRANSLATION_HIDDEN": 1,
	}
)

func (x TranslationStatus) Enum() *TranslationStatus {
	p := new(TranslationStatus)
	*p = x
	return p
}

func (x TranslationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranslationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[7].Descriptor()
}

func (TranslationStatus) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[7]
}

func (x TranslationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranslationStatus.Descriptor instead.
func (TranslationStatus) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{7}
}

var File_const_proto protoreflect.FileDescriptor

var file_const_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x2a, 0x46, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x49,
	0x53, 0x5f, 0x42, 0x41, 0x4e, 0x4e, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x52, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52,
	0x4f, 0x4c, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x4c, 0x41,
	0x54, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x4f,
	0x4c, 0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x2a, 0x44,
	0x0a, 0x10, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x44, 0x45,
	0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x01, 0x2a, 0x6a, 0x0a, 0x1c, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x1e, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x49, 0x5a, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x26, 0x0a, 0x22, 0x4c, 0x4f, 0x43, 0x41,
	0x4c, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46,
	0x49, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01,
	0x2a, 0x3e, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x41, 0x54, 0x45, 0x47,
	0x4f, 0x52, 0x59, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01,
	0x2a, 0x4a, 0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x49,
	0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12,
	0x1b, 0x0a, 0x17, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x24, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45,
	0x10, 0x01, 0x2a, 0x43, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x52, 0x41, 0x4e, 0x53,
	0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x48,
	0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_const_proto_rawDescOnce sync.Once
	file_const_proto_rawDescData = file_const_proto_rawDesc
)

func file_const_proto_rawDescGZIP() []byte {
	file_const_proto_rawDescOnce.Do(func() {
		file_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_const_proto_rawDescData)
	})
	return file_const_proto_rawDescData
}

var file_const_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_const_proto_goTypes = []interface{}{
	(UserStatus)(0),                   // 0: api.UserStatus
	(UserRole)(0),                     // 1: api.UserRole
	(IdentifierStatus)(0),             // 2: api.IdentifierStatus
	(LocalizationIdentifierStatus)(0), // 3: api.LocalizationIdentifierStatus
	(CategoryStatus)(0),               // 4: api.CategoryStatus
	(LocalizationStatus)(0),           // 5: api.LocalizationStatus
	(Status)(0),                       // 6: api.Status
	(TranslationStatus)(0),            // 7: api.TranslationStatus
}
var file_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_const_proto_init() }
func file_const_proto_init() {
	if File_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_const_proto_rawDesc,
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_const_proto_goTypes,
		DependencyIndexes: file_const_proto_depIdxs,
		EnumInfos:         file_const_proto_enumTypes,
	}.Build()
	File_const_proto = out.File
	file_const_proto_rawDesc = nil
	file_const_proto_goTypes = nil
	file_const_proto_depIdxs = nil
}
