// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: freon_service.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_freon_service_proto protoreflect.FileDescriptor

var file_freon_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x72, 0x65, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x12, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x56,
	0x0a, 0x0c, 0x46, 0x72, 0x65, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x3b, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_freon_service_proto_goTypes = []interface{}{
	(*GetLocalizationsReq)(nil), // 0: api.GetLocalizationsReq
	(*GetLocalizationsRes)(nil), // 1: api.GetLocalizationsRes
}
var file_freon_service_proto_depIdxs = []int32{
	0, // 0: api.FreonService.GetLocalizations:input_type -> api.GetLocalizationsReq
	1, // 1: api.FreonService.GetLocalizations:output_type -> api.GetLocalizationsRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_freon_service_proto_init() }
func file_freon_service_proto_init() {
	if File_freon_service_proto != nil {
		return
	}
	file_localization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_freon_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_freon_service_proto_goTypes,
		DependencyIndexes: file_freon_service_proto_depIdxs,
	}.Build()
	File_freon_service_proto = out.File
	file_freon_service_proto_rawDesc = nil
	file_freon_service_proto_goTypes = nil
	file_freon_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FreonServiceClient is the client API for FreonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FreonServiceClient interface {
	GetLocalizations(ctx context.Context, in *GetLocalizationsReq, opts ...grpc.CallOption) (*GetLocalizationsRes, error)
}

type freonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFreonServiceClient(cc grpc.ClientConnInterface) FreonServiceClient {
	return &freonServiceClient{cc}
}

func (c *freonServiceClient) GetLocalizations(ctx context.Context, in *GetLocalizationsReq, opts ...grpc.CallOption) (*GetLocalizationsRes, error) {
	out := new(GetLocalizationsRes)
	err := c.cc.Invoke(ctx, "/api.FreonService/GetLocalizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreonServiceServer is the server API for FreonService service.
type FreonServiceServer interface {
	GetLocalizations(context.Context, *GetLocalizationsReq) (*GetLocalizationsRes, error)
}

// UnimplementedFreonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFreonServiceServer struct {
}

func (*UnimplementedFreonServiceServer) GetLocalizations(context.Context, *GetLocalizationsReq) (*GetLocalizationsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalizations not implemented")
}

func RegisterFreonServiceServer(s *grpc.Server, srv FreonServiceServer) {
	s.RegisterService(&_FreonService_serviceDesc, srv)
}

func _FreonService_GetLocalizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalizationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreonServiceServer).GetLocalizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FreonService/GetLocalizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreonServiceServer).GetLocalizations(ctx, req.(*GetLocalizationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _FreonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.FreonService",
	HandlerType: (*FreonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocalizations",
			Handler:    _FreonService_GetLocalizations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "freon_service.proto",
}
