// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: translation.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Translation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentifierName string `protobuf:"bytes,1,opt,name=identifier_name,json=identifierName,proto3" json:"identifier_name,omitempty"`
	Text           string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Translation) Reset() {
	*x = Translation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Translation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation) ProtoMessage() {}

func (x *Translation) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation.ProtoReflect.Descriptor instead.
func (*Translation) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{0}
}

func (x *Translation) GetIdentifierName() string {
	if x != nil {
		return x.IdentifierName
	}
	return ""
}

func (x *Translation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GroupedTranslations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locale       string         `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Translations []*Translation `protobuf:"bytes,2,rep,name=translations,proto3" json:"translations,omitempty"`
}

func (x *GroupedTranslations) Reset() {
	*x = GroupedTranslations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupedTranslations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedTranslations) ProtoMessage() {}

func (x *GroupedTranslations) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedTranslations.ProtoReflect.Descriptor instead.
func (*GroupedTranslations) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{1}
}

func (x *GroupedTranslations) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *GroupedTranslations) GetTranslations() []*Translation {
	if x != nil {
		return x.Translations
	}
	return nil
}

type GetListTranslationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locales []string `protobuf:"bytes,1,rep,name=locales,proto3" json:"locales,omitempty"` // localization local
}

func (x *GetListTranslationsReq) Reset() {
	*x = GetListTranslationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListTranslationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListTranslationsReq) ProtoMessage() {}

func (x *GetListTranslationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListTranslationsReq.ProtoReflect.Descriptor instead.
func (*GetListTranslationsReq) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{2}
}

func (x *GetListTranslationsReq) GetLocales() []string {
	if x != nil {
		return x.Locales
	}
	return nil
}

type GetListTranslationsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupedTranslations []*GroupedTranslations `protobuf:"bytes,1,rep,name=grouped_translations,json=groupedTranslations,proto3" json:"grouped_translations,omitempty"`
}

func (x *GetListTranslationsRes) Reset() {
	*x = GetListTranslationsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListTranslationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListTranslationsRes) ProtoMessage() {}

func (x *GetListTranslationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListTranslationsRes.ProtoReflect.Descriptor instead.
func (*GetListTranslationsRes) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{3}
}

func (x *GetListTranslationsRes) GetGroupedTranslations() []*GroupedTranslations {
	if x != nil {
		return x.GroupedTranslations
	}
	return nil
}

type GetTranslationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locale         string `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`                                       // localization local
	IdentifierName string `protobuf:"bytes,2,opt,name=identifier_name,json=identifierName,proto3" json:"identifier_name,omitempty"` // identifier name
}

func (x *GetTranslationReq) Reset() {
	*x = GetTranslationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTranslationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationReq) ProtoMessage() {}

func (x *GetTranslationReq) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationReq.ProtoReflect.Descriptor instead.
func (*GetTranslationReq) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{4}
}

func (x *GetTranslationReq) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *GetTranslationReq) GetIdentifierName() string {
	if x != nil {
		return x.IdentifierName
	}
	return ""
}

type GetTranslationRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translation *Translation `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
}

func (x *GetTranslationRes) Reset() {
	*x = GetTranslationRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTranslationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationRes) ProtoMessage() {}

func (x *GetTranslationRes) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationRes.ProtoReflect.Descriptor instead.
func (*GetTranslationRes) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{5}
}

func (x *GetTranslationRes) GetTranslation() *Translation {
	if x != nil {
		return x.Translation
	}
	return nil
}

var File_translation_proto protoreflect.FileDescriptor

var file_translation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x4a, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x63, 0x0a, 0x13, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x65, 0x64, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x32, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x73, 0x22, 0x65, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x14, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x65, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x13, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x32, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_translation_proto_rawDescOnce sync.Once
	file_translation_proto_rawDescData = file_translation_proto_rawDesc
)

func file_translation_proto_rawDescGZIP() []byte {
	file_translation_proto_rawDescOnce.Do(func() {
		file_translation_proto_rawDescData = protoimpl.X.CompressGZIP(file_translation_proto_rawDescData)
	})
	return file_translation_proto_rawDescData
}

var file_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_translation_proto_goTypes = []interface{}{
	(*Translation)(nil),            // 0: api.Translation
	(*GroupedTranslations)(nil),    // 1: api.GroupedTranslations
	(*GetListTranslationsReq)(nil), // 2: api.GetListTranslationsReq
	(*GetListTranslationsRes)(nil), // 3: api.GetListTranslationsRes
	(*GetTranslationReq)(nil),      // 4: api.GetTranslationReq
	(*GetTranslationRes)(nil),      // 5: api.GetTranslationRes
}
var file_translation_proto_depIdxs = []int32{
	0, // 0: api.GroupedTranslations.translations:type_name -> api.Translation
	1, // 1: api.GetListTranslationsRes.grouped_translations:type_name -> api.GroupedTranslations
	0, // 2: api.GetTranslationRes.translation:type_name -> api.Translation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_translation_proto_init() }
func file_translation_proto_init() {
	if File_translation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_translation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Translation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupedTranslations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListTranslationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListTranslationsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTranslationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTranslationRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_translation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_translation_proto_goTypes,
		DependencyIndexes: file_translation_proto_depIdxs,
		MessageInfos:      file_translation_proto_msgTypes,
	}.Build()
	File_translation_proto = out.File
	file_translation_proto_rawDesc = nil
	file_translation_proto_goTypes = nil
	file_translation_proto_depIdxs = nil
}
