export const LIST_IDENTIFIERS_REQUEST = 'LIST_IDENTIFIERS_REQUEST';
export const LIST_IDENTIFIERS_SUCCESS = 'LIST_IDENTIFIERS_SUCCESS';
export const LIST_IDENTIFIERS_ERROR = 'LIST_IDENTIFIERS_ERROR';

export const CREATE_IDENTIFIER_REQUEST = 'CREATE_IDENTIFIER_REQUEST';
export const CREATE_IDENTIFIER_SUCCESS = 'CREATE_IDENTIFIER_SUCCESS';
export const CREATE_IDENTIFIER_ERROR = 'CREATE_IDENTIFIER_ERROR';

export const UPDATE_IDENTIFIER_REQUEST = 'UPDATE_IDENTIFIER_REQUEST';
export const UPDATE_IDENTIFIER_SUCCESS = 'UPDATE_IDENTIFIER_SUCCESS';
export const UPDATE_IDENTIFIER_ERROR = 'UPDATE_IDENTIFIER_ERROR';

export const DELETE_IDENTIFIER_REQUEST = 'DELETE_IDENTIFIER_REQUEST';
export const DELETE_IDENTIFIER_SUCCESS = 'DELETE_IDENTIFIER_SUCCESS';
export const DELETE_IDENTIFIER_ERROR = 'DELETE_IDENTIFIER_ERROR';
