// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Freon Frontend
//
//  Frontend Server for rest api
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/internal
//  Version: 0.0.3
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
