version: '3.8'

services:
  libra:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      LT_DEBUG: "True"
      LT_LOAD_ONLY: "en,ru,de"
      LT_HOST: "0.0.0.0"
      LT_PORT: "5000"
      LT_FRONTEND_LANGUAGE_SOURCE: "ru"
      LT_FRONTEND_LANGUAGE_TARGET: "en"
