// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: localization.proto

package freonApi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Localization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Locale   string `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	LangName string `protobuf:"bytes,3,opt,name=lang_name,json=langName,proto3" json:"lang_name,omitempty"`
}

func (x *Localization) Reset() {
	*x = Localization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_localization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Localization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Localization) ProtoMessage() {}

func (x *Localization) ProtoReflect() protoreflect.Message {
	mi := &file_localization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Localization.ProtoReflect.Descriptor instead.
func (*Localization) Descriptor() ([]byte, []int) {
	return file_localization_proto_rawDescGZIP(), []int{0}
}

func (x *Localization) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Localization) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Localization) GetLangName() string {
	if x != nil {
		return x.LangName
	}
	return ""
}

type GetListLocalizationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListLocalizationsReq) Reset() {
	*x = GetListLocalizationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_localization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListLocalizationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListLocalizationsReq) ProtoMessage() {}

func (x *GetListLocalizationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_localization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListLocalizationsReq.ProtoReflect.Descriptor instead.
func (*GetListLocalizationsReq) Descriptor() ([]byte, []int) {
	return file_localization_proto_rawDescGZIP(), []int{1}
}

type GetListLocalizationsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Localizations []*Localization `protobuf:"bytes,1,rep,name=localizations,proto3" json:"localizations,omitempty"`
}

func (x *GetListLocalizationsRes) Reset() {
	*x = GetListLocalizationsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_localization_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListLocalizationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListLocalizationsRes) ProtoMessage() {}

func (x *GetListLocalizationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_localization_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListLocalizationsRes.ProtoReflect.Descriptor instead.
func (*GetListLocalizationsRes) Descriptor() ([]byte, []int) {
	return file_localization_proto_rawDescGZIP(), []int{2}
}

func (x *GetListLocalizationsRes) GetLocalizations() []*Localization {
	if x != nil {
		return x.Localizations
	}
	return nil
}

var File_localization_proto protoreflect.FileDescriptor

var file_localization_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x72, 0x65, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x0c, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x22, 0x54, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x66, 0x72, 0x65, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x72, 0x65, 0x6f, 0x6e, 0x41, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_localization_proto_rawDescOnce sync.Once
	file_localization_proto_rawDescData = file_localization_proto_rawDesc
)

func file_localization_proto_rawDescGZIP() []byte {
	file_localization_proto_rawDescOnce.Do(func() {
		file_localization_proto_rawDescData = protoimpl.X.CompressGZIP(file_localization_proto_rawDescData)
	})
	return file_localization_proto_rawDescData
}

var file_localization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_localization_proto_goTypes = []interface{}{
	(*Localization)(nil),            // 0: freon.Localization
	(*GetListLocalizationsReq)(nil), // 1: freon.GetListLocalizationsReq
	(*GetListLocalizationsRes)(nil), // 2: freon.GetListLocalizationsRes
}
var file_localization_proto_depIdxs = []int32{
	0, // 0: freon.GetListLocalizationsRes.localizations:type_name -> freon.Localization
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_localization_proto_init() }
func file_localization_proto_init() {
	if File_localization_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_localization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Localization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_localization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListLocalizationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_localization_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListLocalizationsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_localization_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_localization_proto_goTypes,
		DependencyIndexes: file_localization_proto_depIdxs,
		MessageInfos:      file_localization_proto_msgTypes,
	}.Build()
	File_localization_proto = out.File
	file_localization_proto_rawDesc = nil
	file_localization_proto_goTypes = nil
	file_localization_proto_depIdxs = nil
}
