// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dao

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type localizationTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *localizationTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("localizations").
func (v *localizationTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *localizationTableType) Columns() []string {
	return []string{
		"id",
		"creator_id",
		"locale",
		"icon",
		"lang_name",
		"status",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *localizationTableType) NewStruct() reform.Struct {
	return new(Localization)
}

// NewRecord makes a new record for that table.
func (v *localizationTableType) NewRecord() reform.Record {
	return new(Localization)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *localizationTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// LocalizationTable represents localizations view or table in SQL database.
var LocalizationTable = &localizationTableType{
	s: parse.StructInfo{
		Type:    "Localization",
		SQLName: "localizations",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int64", Column: "id"},
			{Name: "CreatorID", Type: "int64", Column: "creator_id"},
			{Name: "Locale", Type: "string", Column: "locale"},
			{Name: "Icon", Type: "string", Column: "icon"},
			{Name: "LanguageName", Type: "string", Column: "lang_name"},
			{Name: "Status", Type: "int64", Column: "status"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "*time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Localization).Values(),
}

// String returns a string representation of this struct or record.
func (s Localization) String() string {
	res := make([]string, 8)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "CreatorID: " + reform.Inspect(s.CreatorID, true)
	res[2] = "Locale: " + reform.Inspect(s.Locale, true)
	res[3] = "Icon: " + reform.Inspect(s.Icon, true)
	res[4] = "LanguageName: " + reform.Inspect(s.LanguageName, true)
	res[5] = "Status: " + reform.Inspect(s.Status, true)
	res[6] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[7] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Localization) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.CreatorID,
		s.Locale,
		s.Icon,
		s.LanguageName,
		s.Status,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Localization) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.CreatorID,
		&s.Locale,
		&s.Icon,
		&s.LanguageName,
		&s.Status,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *Localization) View() reform.View {
	return LocalizationTable
}

// Table returns Table object for that record.
func (s *Localization) Table() reform.Table {
	return LocalizationTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Localization) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Localization) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Localization) HasPK() bool {
	return s.ID != LocalizationTable.z[LocalizationTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Localization) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = LocalizationTable
	_ reform.Struct = (*Localization)(nil)
	_ reform.Table  = LocalizationTable
	_ reform.Record = (*Localization)(nil)
	_ fmt.Stringer  = (*Localization)(nil)
)

func init() {
	parse.AssertUpToDate(&LocalizationTable.s, new(Localization))
}
