// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dao

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type localizationIdentifierTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *localizationIdentifierTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("localization_identifiers").
func (v *localizationIdentifierTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *localizationIdentifierTableType) Columns() []string {
	return []string{
		"id",
		"localization_id",
		"identifier_id",
		"status",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *localizationIdentifierTableType) NewStruct() reform.Struct {
	return new(LocalizationIdentifier)
}

// NewRecord makes a new record for that table.
func (v *localizationIdentifierTableType) NewRecord() reform.Record {
	return new(LocalizationIdentifier)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *localizationIdentifierTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// LocalizationIdentifierTable represents localization_identifiers view or table in SQL database.
var LocalizationIdentifierTable = &localizationIdentifierTableType{
	s: parse.StructInfo{
		Type:    "LocalizationIdentifier",
		SQLName: "localization_identifiers",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int64", Column: "id"},
			{Name: "LocalizationID", Type: "int64", Column: "localization_id"},
			{Name: "IdentifierID", Type: "int64", Column: "identifier_id"},
			{Name: "Status", Type: "int64", Column: "status"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "*time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(LocalizationIdentifier).Values(),
}

// String returns a string representation of this struct or record.
func (s LocalizationIdentifier) String() string {
	res := make([]string, 6)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "LocalizationID: " + reform.Inspect(s.LocalizationID, true)
	res[2] = "IdentifierID: " + reform.Inspect(s.IdentifierID, true)
	res[3] = "Status: " + reform.Inspect(s.Status, true)
	res[4] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[5] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *LocalizationIdentifier) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.LocalizationID,
		s.IdentifierID,
		s.Status,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *LocalizationIdentifier) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.LocalizationID,
		&s.IdentifierID,
		&s.Status,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *LocalizationIdentifier) View() reform.View {
	return LocalizationIdentifierTable
}

// Table returns Table object for that record.
func (s *LocalizationIdentifier) Table() reform.Table {
	return LocalizationIdentifierTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *LocalizationIdentifier) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *LocalizationIdentifier) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *LocalizationIdentifier) HasPK() bool {
	return s.ID != LocalizationIdentifierTable.z[LocalizationIdentifierTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *LocalizationIdentifier) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = LocalizationIdentifierTable
	_ reform.Struct = (*LocalizationIdentifier)(nil)
	_ reform.Table  = LocalizationIdentifierTable
	_ reform.Record = (*LocalizationIdentifier)(nil)
	_ fmt.Stringer  = (*LocalizationIdentifier)(nil)
)

func init() {
	parse.AssertUpToDate(&LocalizationIdentifierTable.s, new(LocalizationIdentifier))
}
