// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dao

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type translationFileTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *translationFileTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("translation_files").
func (v *translationFileTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *translationFileTableType) Columns() []string {
	return []string{"id", "localization_id", "creator_id", "name", "path", "platform", "status", "storage_type", "created_at", "updated_at"}
}

// NewStruct makes a new struct for that view or table.
func (v *translationFileTableType) NewStruct() reform.Struct {
	return new(TranslationFile)
}

// NewRecord makes a new record for that table.
func (v *translationFileTableType) NewRecord() reform.Record {
	return new(TranslationFile)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *translationFileTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// TranslationFileTable represents translation_files view or table in SQL database.
var TranslationFileTable = &translationFileTableType{
	s: parse.StructInfo{Type: "TranslationFile", SQLSchema: "", SQLName: "translation_files", Fields: []parse.FieldInfo{{Name: "ID", Type: "int64", Column: "id"}, {Name: "LocalizationID", Type: "int64", Column: "localization_id"}, {Name: "CreatorID", Type: "int64", Column: "creator_id"}, {Name: "Name", Type: "string", Column: "name"}, {Name: "Path", Type: "string", Column: "path"}, {Name: "Platform", Type: "int64", Column: "platform"}, {Name: "Status", Type: "int64", Column: "status"}, {Name: "StorageType", Type: "int64", Column: "storage_type"}, {Name: "CreatedAt", Type: "time.Time", Column: "created_at"}, {Name: "UpdatedAt", Type: "*time.Time", Column: "updated_at"}}, PKFieldIndex: 0},
	z: new(TranslationFile).Values(),
}

// String returns a string representation of this struct or record.
func (s TranslationFile) String() string {
	res := make([]string, 10)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "LocalizationID: " + reform.Inspect(s.LocalizationID, true)
	res[2] = "CreatorID: " + reform.Inspect(s.CreatorID, true)
	res[3] = "Name: " + reform.Inspect(s.Name, true)
	res[4] = "Path: " + reform.Inspect(s.Path, true)
	res[5] = "Platform: " + reform.Inspect(s.Platform, true)
	res[6] = "Status: " + reform.Inspect(s.Status, true)
	res[7] = "StorageType: " + reform.Inspect(s.StorageType, true)
	res[8] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[9] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *TranslationFile) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.LocalizationID,
		s.CreatorID,
		s.Name,
		s.Path,
		s.Platform,
		s.Status,
		s.StorageType,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *TranslationFile) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.LocalizationID,
		&s.CreatorID,
		&s.Name,
		&s.Path,
		&s.Platform,
		&s.Status,
		&s.StorageType,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *TranslationFile) View() reform.View {
	return TranslationFileTable
}

// Table returns Table object for that record.
func (s *TranslationFile) Table() reform.Table {
	return TranslationFileTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *TranslationFile) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *TranslationFile) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *TranslationFile) HasPK() bool {
	return s.ID != TranslationFileTable.z[TranslationFileTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *TranslationFile) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int64(i64)
	} else {
		s.ID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = TranslationFileTable
	_ reform.Struct = (*TranslationFile)(nil)
	_ reform.Table  = TranslationFileTable
	_ reform.Record = (*TranslationFile)(nil)
	_ fmt.Stringer  = (*TranslationFile)(nil)
)

func init() {
	parse.AssertUpToDate(&TranslationFileTable.s, new(TranslationFile))
}
