// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dao

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type userSessionTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *userSessionTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("user_sessions").
func (v *userSessionTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *userSessionTableType) Columns() []string {
	return []string{
		"id",
		"user_id",
		"token",
		"active",
		"created_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *userSessionTableType) NewStruct() reform.Struct {
	return new(UserSession)
}

// NewRecord makes a new record for that table.
func (v *userSessionTableType) NewRecord() reform.Record {
	return new(UserSession)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *userSessionTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// UserSessionTable represents user_sessions view or table in SQL database.
var UserSessionTable = &userSessionTableType{
	s: parse.StructInfo{
		Type:    "UserSession",
		SQLName: "user_sessions",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int64", Column: "id"},
			{Name: "UserID", Type: "int64", Column: "user_id"},
			{Name: "Token", Type: "string", Column: "token"},
			{Name: "Active", Type: "bool", Column: "active"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(UserSession).Values(),
}

// String returns a string representation of this struct or record.
func (s UserSession) String() string {
	res := make([]string, 5)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "UserID: " + reform.Inspect(s.UserID, true)
	res[2] = "Token: " + reform.Inspect(s.Token, true)
	res[3] = "Active: " + reform.Inspect(s.Active, true)
	res[4] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *UserSession) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.UserID,
		s.Token,
		s.Active,
		s.CreatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *UserSession) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.UserID,
		&s.Token,
		&s.Active,
		&s.CreatedAt,
	}
}

// View returns View object for that struct.
func (s *UserSession) View() reform.View {
	return UserSessionTable
}

// Table returns Table object for that record.
func (s *UserSession) Table() reform.Table {
	return UserSessionTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *UserSession) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *UserSession) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *UserSession) HasPK() bool {
	return s.ID != UserSessionTable.z[UserSessionTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *UserSession) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = UserSessionTable
	_ reform.Struct = (*UserSession)(nil)
	_ reform.Table  = UserSessionTable
	_ reform.Record = (*UserSession)(nil)
	_ fmt.Stringer  = (*UserSession)(nil)
)

func init() {
	parse.AssertUpToDate(&UserSessionTable.s, new(UserSession))
}
