export const LIST_LOCALIZATIONS_REQUEST = 'LIST_LOCALIZATIONS_REQUEST';
export const LIST_LOCALIZATIONS_SUCCESS = 'LIST_LOCALIZATIONS_SUCCESS';
export const LIST_LOCALIZATIONS_ERROR = 'LIST_LOCALIZATIONS_ERROR';

export const CREATE_LOCALIZATION_REQUEST = 'CREATE_LOCALIZATION_REQUEST';
export const CREATE_LOCALIZATION_SUCCESS = 'CREATE_LOCALIZATION_SUCCESS';
export const CREATE_LOCALIZATION_ERROR = 'CREATE_LOCALIZATION_ERROR';

export const UPDATE_LOCALIZATION_REQUEST = 'UPDATE_LOCALIZATION_REQUEST';
export const UPDATE_LOCALIZATION_SUCCESS = 'UPDATE_LOCALIZATION_SUCCESS';
export const UPDATE_LOCALIZATION_ERROR = 'UPDATE_LOCALIZATION_ERROR';
