export const LIST_SETTINGS_REQUEST = 'LIST_SETTINGS_REQUEST';
export const LIST_SETTINGS_SUCCESS = 'LIST_SETTINGS_SUCCESS';
export const LIST_SETTINGS_ERROR = 'LIST_SETTINGS_ERROR';

export const UPDATE_SETTING_STORAGE_REQUEST = 'UPDATE_SETTING_STORAGE_REQUEST';
export const UPDATE_SETTING_STORAGE_SUCCESS = 'UPDATE_SETTING_STORAGE_SUCCESS';
export const UPDATE_SETTING_STORAGE_ERROR = 'UPDATE_SETTING_STORAGE_ERROR';

export const UPDATE_SETTING_TRANSLATION_REQUEST = 'UPDATE_SETTING_TRANSLATION_REQUEST';
export const UPDATE_SETTING_TRANSLATION_SUCCESS = 'UPDATE_SETTING_TRANSLATION_SUCCESS';
export const UPDATE_SETTING_TRANSLATION_ERROR = 'UPDATE_SETTING_TRANSLATION_ERROR';
