// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/api/openapi/frontend/model"
)

// AutoTranslationOKCode is the HTTP code returned for type AutoTranslationOK
const AutoTranslationOKCode int = 200

/*AutoTranslationOK OK

swagger:response autoTranslationOK
*/
type AutoTranslationOK struct {

	/*
	  In: Body
	*/
	Payload *AutoTranslationOKBody `json:"body,omitempty"`
}

// NewAutoTranslationOK creates AutoTranslationOK with default headers values
func NewAutoTranslationOK() *AutoTranslationOK {

	return &AutoTranslationOK{}
}

// WithPayload adds the payload to the auto translation o k response
func (o *AutoTranslationOK) WithPayload(payload *AutoTranslationOKBody) *AutoTranslationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auto translation o k response
func (o *AutoTranslationOK) SetPayload(payload *AutoTranslationOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AutoTranslationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *AutoTranslationOK) AutoTranslationResponder() {}

/*AutoTranslationDefault General errors using same model as used by go-swagger for validation errors.

swagger:response autoTranslationDefault
*/
type AutoTranslationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewAutoTranslationDefault creates AutoTranslationDefault with default headers values
func NewAutoTranslationDefault(code int) *AutoTranslationDefault {
	if code <= 0 {
		code = 500
	}

	return &AutoTranslationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the auto translation default response
func (o *AutoTranslationDefault) WithStatusCode(code int) *AutoTranslationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the auto translation default response
func (o *AutoTranslationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the auto translation default response
func (o *AutoTranslationDefault) WithPayload(payload *model.Error) *AutoTranslationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auto translation default response
func (o *AutoTranslationDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AutoTranslationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *AutoTranslationDefault) AutoTranslationResponder() {}

type AutoTranslationNotImplementedResponder struct {
	middleware.Responder
}

func (*AutoTranslationNotImplementedResponder) AutoTranslationResponder() {}

func AutoTranslationNotImplemented() AutoTranslationResponder {
	return &AutoTranslationNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.AutoTranslation has not yet been implemented",
		),
	}
}

type AutoTranslationResponder interface {
	middleware.Responder
	AutoTranslationResponder()
}
