// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/MarcSky/freon/api/openapi/frontend/model"
)

// CreateIdentifierNoContentCode is the HTTP code returned for type CreateIdentifierNoContent
const CreateIdentifierNoContentCode int = 204

/*CreateIdentifierNoContent No content in answer

swagger:response createIdentifierNoContent
*/
type CreateIdentifierNoContent struct {
}

// NewCreateIdentifierNoContent creates CreateIdentifierNoContent with default headers values
func NewCreateIdentifierNoContent() *CreateIdentifierNoContent {

	return &CreateIdentifierNoContent{}
}

// WriteResponse to the client
func (o *CreateIdentifierNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *CreateIdentifierNoContent) CreateIdentifierResponder() {}

/*CreateIdentifierDefault General errors using same model as used by go-swagger for validation errors.

swagger:response createIdentifierDefault
*/
type CreateIdentifierDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewCreateIdentifierDefault creates CreateIdentifierDefault with default headers values
func NewCreateIdentifierDefault(code int) *CreateIdentifierDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateIdentifierDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create identifier default response
func (o *CreateIdentifierDefault) WithStatusCode(code int) *CreateIdentifierDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create identifier default response
func (o *CreateIdentifierDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create identifier default response
func (o *CreateIdentifierDefault) WithPayload(payload *model.Error) *CreateIdentifierDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create identifier default response
func (o *CreateIdentifierDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateIdentifierDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *CreateIdentifierDefault) CreateIdentifierResponder() {}

type CreateIdentifierNotImplementedResponder struct {
	middleware.Responder
}

func (*CreateIdentifierNotImplementedResponder) CreateIdentifierResponder() {}

func CreateIdentifierNotImplemented() CreateIdentifierResponder {
	return &CreateIdentifierNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.CreateIdentifier has not yet been implemented",
		),
	}
}

type CreateIdentifierResponder interface {
	middleware.Responder
	CreateIdentifierResponder()
}
