// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/api/openapi/frontend/model"
)

// CreateLocalizationNoContentCode is the HTTP code returned for type CreateLocalizationNoContent
const CreateLocalizationNoContentCode int = 204

/*CreateLocalizationNoContent No content in answer

swagger:response createLocalizationNoContent
*/
type CreateLocalizationNoContent struct {
}

// NewCreateLocalizationNoContent creates CreateLocalizationNoContent with default headers values
func NewCreateLocalizationNoContent() *CreateLocalizationNoContent {

	return &CreateLocalizationNoContent{}
}

// WriteResponse to the client
func (o *CreateLocalizationNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *CreateLocalizationNoContent) CreateLocalizationResponder() {}

/*CreateLocalizationDefault General errors using same model as used by go-swagger for validation errors.

swagger:response createLocalizationDefault
*/
type CreateLocalizationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewCreateLocalizationDefault creates CreateLocalizationDefault with default headers values
func NewCreateLocalizationDefault(code int) *CreateLocalizationDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateLocalizationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create localization default response
func (o *CreateLocalizationDefault) WithStatusCode(code int) *CreateLocalizationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create localization default response
func (o *CreateLocalizationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create localization default response
func (o *CreateLocalizationDefault) WithPayload(payload *model.Error) *CreateLocalizationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create localization default response
func (o *CreateLocalizationDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateLocalizationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *CreateLocalizationDefault) CreateLocalizationResponder() {}

type CreateLocalizationNotImplementedResponder struct {
	middleware.Responder
}

func (*CreateLocalizationNotImplementedResponder) CreateLocalizationResponder() {}

func CreateLocalizationNotImplemented() CreateLocalizationResponder {
	return &CreateLocalizationNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.CreateLocalization has not yet been implemented",
		),
	}
}

type CreateLocalizationResponder interface {
	middleware.Responder
	CreateLocalizationResponder()
}
