// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"bytes"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/MarcSky/freon/internal/app"
)

// CreateCategoryHandlerFunc turns a function with the right signature into a create category handler
type CreateCategoryHandlerFunc func(CreateCategoryParams, *app.UserSession) CreateCategoryResponder

// Handle executing the request and returning a response
func (fn CreateCategoryHandlerFunc) Handle(params CreateCategoryParams, principal *app.UserSession) CreateCategoryResponder {
	return fn(params, principal)
}

// CreateCategoryHandler interface for that can handle valid create category params
type CreateCategoryHandler interface {
	Handle(CreateCategoryParams, *app.UserSession) CreateCategoryResponder
}

// NewCreateCategory creates a new http.Handler for the create category operation
func NewCreateCategory(ctx *middleware.Context, handler CreateCategoryHandler) *CreateCategory {
	return &CreateCategory{Context: ctx, Handler: handler}
}

/*CreateCategory swagger:route POST /category createCategory

create new category

*/
type CreateCategory struct {
	Context *middleware.Context
	Handler CreateCategoryHandler
}

func (o *CreateCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateCategoryParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *app.UserSession
	if uprinc != nil {
		principal = uprinc.(*app.UserSession) // this is really a app.UserSession, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateCategoryBody create category body
//
// swagger:model CreateCategoryBody
type CreateCategoryBody struct {

	// name
	// Required: true
	// Max Length: 255
	// Min Length: 1
	Name *string `json:"name"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *CreateCategoryBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// name
		// Required: true
		// Max Length: 255
		// Min Length: 1
		Name *string `json:"name"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.Name = props.Name
	return nil
}

// Validate validates this create category body
func (o *CreateCategoryBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCategoryBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	if err := validate.MinLength("args"+"."+"name", "body", string(*o.Name), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("args"+"."+"name", "body", string(*o.Name), 255); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateCategoryBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateCategoryBody) UnmarshalBinary(b []byte) error {
	var res CreateCategoryBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
