// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/api/openapi/frontend/model"
)

// CreateTranslationFilesNoContentCode is the HTTP code returned for type CreateTranslationFilesNoContent
const CreateTranslationFilesNoContentCode int = 204

/*CreateTranslationFilesNoContent No content in answer

swagger:response createTranslationFilesNoContent
*/
type CreateTranslationFilesNoContent struct {
}

// NewCreateTranslationFilesNoContent creates CreateTranslationFilesNoContent with default headers values
func NewCreateTranslationFilesNoContent() *CreateTranslationFilesNoContent {

	return &CreateTranslationFilesNoContent{}
}

// WriteResponse to the client
func (o *CreateTranslationFilesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *CreateTranslationFilesNoContent) CreateTranslationFilesResponder() {}

/*CreateTranslationFilesDefault General errors using same model as used by go-swagger for validation errors.

swagger:response createTranslationFilesDefault
*/
type CreateTranslationFilesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewCreateTranslationFilesDefault creates CreateTranslationFilesDefault with default headers values
func NewCreateTranslationFilesDefault(code int) *CreateTranslationFilesDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateTranslationFilesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create translation files default response
func (o *CreateTranslationFilesDefault) WithStatusCode(code int) *CreateTranslationFilesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create translation files default response
func (o *CreateTranslationFilesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create translation files default response
func (o *CreateTranslationFilesDefault) WithPayload(payload *model.Error) *CreateTranslationFilesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create translation files default response
func (o *CreateTranslationFilesDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTranslationFilesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *CreateTranslationFilesDefault) CreateTranslationFilesResponder() {}

type CreateTranslationFilesNotImplementedResponder struct {
	middleware.Responder
}

func (*CreateTranslationFilesNotImplementedResponder) CreateTranslationFilesResponder() {}

func CreateTranslationFilesNotImplemented() CreateTranslationFilesResponder {
	return &CreateTranslationFilesNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.CreateTranslationFiles has not yet been implemented",
		),
	}
}

type CreateTranslationFilesResponder interface {
	middleware.Responder
	CreateTranslationFilesResponder()
}
