// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/api/openapi/frontend/model"
)

// DeleteTranslationNoContentCode is the HTTP code returned for type DeleteTranslationNoContent
const DeleteTranslationNoContentCode int = 204

/*DeleteTranslationNoContent No content in answer

swagger:response deleteTranslationNoContent
*/
type DeleteTranslationNoContent struct {
}

// NewDeleteTranslationNoContent creates DeleteTranslationNoContent with default headers values
func NewDeleteTranslationNoContent() *DeleteTranslationNoContent {

	return &DeleteTranslationNoContent{}
}

// WriteResponse to the client
func (o *DeleteTranslationNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *DeleteTranslationNoContent) DeleteTranslationResponder() {}

/*DeleteTranslationDefault General errors using same model as used by go-swagger for validation errors.

swagger:response deleteTranslationDefault
*/
type DeleteTranslationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewDeleteTranslationDefault creates DeleteTranslationDefault with default headers values
func NewDeleteTranslationDefault(code int) *DeleteTranslationDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTranslationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete translation default response
func (o *DeleteTranslationDefault) WithStatusCode(code int) *DeleteTranslationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete translation default response
func (o *DeleteTranslationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete translation default response
func (o *DeleteTranslationDefault) WithPayload(payload *model.Error) *DeleteTranslationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete translation default response
func (o *DeleteTranslationDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTranslationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteTranslationDefault) DeleteTranslationResponder() {}

type DeleteTranslationNotImplementedResponder struct {
	middleware.Responder
}

func (*DeleteTranslationNotImplementedResponder) DeleteTranslationResponder() {}

func DeleteTranslationNotImplemented() DeleteTranslationResponder {
	return &DeleteTranslationNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.DeleteTranslation has not yet been implemented",
		),
	}
}

type DeleteTranslationResponder interface {
	middleware.Responder
	DeleteTranslationResponder()
}
