// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/api/openapi/frontend/model"
)

// DeleteCategoryNoContentCode is the HTTP code returned for type DeleteCategoryNoContent
const DeleteCategoryNoContentCode int = 204

/*DeleteCategoryNoContent No content in answer

swagger:response deleteCategoryNoContent
*/
type DeleteCategoryNoContent struct {
}

// NewDeleteCategoryNoContent creates DeleteCategoryNoContent with default headers values
func NewDeleteCategoryNoContent() *DeleteCategoryNoContent {

	return &DeleteCategoryNoContent{}
}

// WriteResponse to the client
func (o *DeleteCategoryNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *DeleteCategoryNoContent) DeleteCategoryResponder() {}

/*DeleteCategoryDefault General errors using same model as used by go-swagger for validation errors.

swagger:response deleteCategoryDefault
*/
type DeleteCategoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewDeleteCategoryDefault creates DeleteCategoryDefault with default headers values
func NewDeleteCategoryDefault(code int) *DeleteCategoryDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteCategoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete category default response
func (o *DeleteCategoryDefault) WithStatusCode(code int) *DeleteCategoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete category default response
func (o *DeleteCategoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete category default response
func (o *DeleteCategoryDefault) WithPayload(payload *model.Error) *DeleteCategoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete category default response
func (o *DeleteCategoryDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCategoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteCategoryDefault) DeleteCategoryResponder() {}

type DeleteCategoryNotImplementedResponder struct {
	middleware.Responder
}

func (*DeleteCategoryNotImplementedResponder) DeleteCategoryResponder() {}

func DeleteCategoryNotImplemented() DeleteCategoryResponder {
	return &DeleteCategoryNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.DeleteCategory has not yet been implemented",
		),
	}
}

type DeleteCategoryResponder interface {
	middleware.Responder
	DeleteCategoryResponder()
}
