// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/MarcSky/freon/internal/app"
)

// DeleteTranslationHandlerFunc turns a function with the right signature into a delete translation handler
type DeleteTranslationHandlerFunc func(DeleteTranslationParams, *app.UserSession) DeleteTranslationResponder

// Handle executing the request and returning a response
func (fn DeleteTranslationHandlerFunc) Handle(params DeleteTranslationParams, principal *app.UserSession) DeleteTranslationResponder {
	return fn(params, principal)
}

// DeleteTranslationHandler interface for that can handle valid delete translation params
type DeleteTranslationHandler interface {
	Handle(DeleteTranslationParams, *app.UserSession) DeleteTranslationResponder
}

// NewDeleteTranslation creates a new http.Handler for the delete translation operation
func NewDeleteTranslation(ctx *middleware.Context, handler DeleteTranslationHandler) *DeleteTranslation {
	return &DeleteTranslation{Context: ctx, Handler: handler}
}

/*DeleteTranslation swagger:route DELETE /translation/{id} deleteTranslation

delete translation

*/
type DeleteTranslation struct {
	Context *middleware.Context
	Handler DeleteTranslationHandler
}

func (o *DeleteTranslation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTranslationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *app.UserSession
	if uprinc != nil {
		principal = uprinc.(*app.UserSession) // this is really a app.UserSession, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
