// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/MarcSky/freon/api/openapi/frontend/model"
)

// DeleteLocalizationNoContentCode is the HTTP code returned for type DeleteLocalizationNoContent
const DeleteLocalizationNoContentCode int = 204

/*DeleteLocalizationNoContent No content in answer

swagger:response deleteLocalizationNoContent
*/
type DeleteLocalizationNoContent struct {
}

// NewDeleteLocalizationNoContent creates DeleteLocalizationNoContent with default headers values
func NewDeleteLocalizationNoContent() *DeleteLocalizationNoContent {

	return &DeleteLocalizationNoContent{}
}

// WriteResponse to the client
func (o *DeleteLocalizationNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *DeleteLocalizationNoContent) DeleteLocalizationResponder() {}

/*DeleteLocalizationDefault General errors using same model as used by go-swagger for validation errors.

swagger:response deleteLocalizationDefault
*/
type DeleteLocalizationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewDeleteLocalizationDefault creates DeleteLocalizationDefault with default headers values
func NewDeleteLocalizationDefault(code int) *DeleteLocalizationDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteLocalizationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete localization default response
func (o *DeleteLocalizationDefault) WithStatusCode(code int) *DeleteLocalizationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete localization default response
func (o *DeleteLocalizationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete localization default response
func (o *DeleteLocalizationDefault) WithPayload(payload *model.Error) *DeleteLocalizationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete localization default response
func (o *DeleteLocalizationDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteLocalizationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteLocalizationDefault) DeleteLocalizationResponder() {}

type DeleteLocalizationNotImplementedResponder struct {
	middleware.Responder
}

func (*DeleteLocalizationNotImplementedResponder) DeleteLocalizationResponder() {}

func DeleteLocalizationNotImplemented() DeleteLocalizationResponder {
	return &DeleteLocalizationNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.DeleteLocalization has not yet been implemented",
		),
	}
}

type DeleteLocalizationResponder interface {
	middleware.Responder
	DeleteLocalizationResponder()
}
