// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/internal/app"
)

// HideTranslationHandlerFunc turns a function with the right signature into a hide translation handler
type HideTranslationHandlerFunc func(HideTranslationParams, *app.UserSession) HideTranslationResponder

// Handle executing the request and returning a response
func (fn HideTranslationHandlerFunc) Handle(params HideTranslationParams, principal *app.UserSession) HideTranslationResponder {
	return fn(params, principal)
}

// HideTranslationHandler interface for that can handle valid hide translation params
type HideTranslationHandler interface {
	Handle(HideTranslationParams, *app.UserSession) HideTranslationResponder
}

// NewHideTranslation creates a new http.Handler for the hide translation operation
func NewHideTranslation(ctx *middleware.Context, handler HideTranslationHandler) *HideTranslation {
	return &HideTranslation{Context: ctx, Handler: handler}
}

/*HideTranslation swagger:route PUT /translation/hide/{id}/{hide} hideTranslation

hide translation

*/
type HideTranslation struct {
	Context *middleware.Context
	Handler HideTranslationHandler
}

func (o *HideTranslation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewHideTranslationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *app.UserSession
	if uprinc != nil {
		principal = uprinc.(*app.UserSession) // this is really a app.UserSession, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
