// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/api/openapi/frontend/model"
)

// StatusTranslationNoContentCode is the HTTP code returned for type StatusTranslationNoContent
const StatusTranslationNoContentCode int = 204

/*StatusTranslationNoContent No content in answer

swagger:response statusTranslationNoContent
*/
type StatusTranslationNoContent struct {
}

// NewStatusTranslationNoContent creates StatusTranslationNoContent with default headers values
func NewStatusTranslationNoContent() *StatusTranslationNoContent {

	return &StatusTranslationNoContent{}
}

// WriteResponse to the client
func (o *StatusTranslationNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *StatusTranslationNoContent) StatusTranslationResponder() {}

/*StatusTranslationDefault General errors using same model as used by go-swagger for validation errors.

swagger:response statusTranslationDefault
*/
type StatusTranslationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewStatusTranslationDefault creates StatusTranslationDefault with default headers values
func NewStatusTranslationDefault(code int) *StatusTranslationDefault {
	if code <= 0 {
		code = 500
	}

	return &StatusTranslationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the status translation default response
func (o *StatusTranslationDefault) WithStatusCode(code int) *StatusTranslationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the status translation default response
func (o *StatusTranslationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the status translation default response
func (o *StatusTranslationDefault) WithPayload(payload *model.Error) *StatusTranslationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status translation default response
func (o *StatusTranslationDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusTranslationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *StatusTranslationDefault) StatusTranslationResponder() {}

type StatusTranslationNotImplementedResponder struct {
	middleware.Responder
}

func (*StatusTranslationNotImplementedResponder) StatusTranslationResponder() {}

func StatusTranslationNotImplemented() StatusTranslationResponder {
	return &StatusTranslationNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.StatusTranslation has not yet been implemented",
		),
	}
}

type StatusTranslationResponder interface {
	middleware.Responder
	StatusTranslationResponder()
}
