// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/api/openapi/frontend/model"
)

// UpdateTranslationNoContentCode is the HTTP code returned for type UpdateTranslationNoContent
const UpdateTranslationNoContentCode int = 204

/*UpdateTranslationNoContent No content in answer

swagger:response updateTranslationNoContent
*/
type UpdateTranslationNoContent struct {
}

// NewUpdateTranslationNoContent creates UpdateTranslationNoContent with default headers values
func NewUpdateTranslationNoContent() *UpdateTranslationNoContent {

	return &UpdateTranslationNoContent{}
}

// WriteResponse to the client
func (o *UpdateTranslationNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *UpdateTranslationNoContent) UpdateTranslationResponder() {}

/*UpdateTranslationDefault General errors using same model as used by go-swagger for validation errors.

swagger:response updateTranslationDefault
*/
type UpdateTranslationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewUpdateTranslationDefault creates UpdateTranslationDefault with default headers values
func NewUpdateTranslationDefault(code int) *UpdateTranslationDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateTranslationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update translation default response
func (o *UpdateTranslationDefault) WithStatusCode(code int) *UpdateTranslationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update translation default response
func (o *UpdateTranslationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update translation default response
func (o *UpdateTranslationDefault) WithPayload(payload *model.Error) *UpdateTranslationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update translation default response
func (o *UpdateTranslationDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateTranslationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *UpdateTranslationDefault) UpdateTranslationResponder() {}

type UpdateTranslationNotImplementedResponder struct {
	middleware.Responder
}

func (*UpdateTranslationNotImplementedResponder) UpdateTranslationResponder() {}

func UpdateTranslationNotImplemented() UpdateTranslationResponder {
	return &UpdateTranslationNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.UpdateTranslation has not yet been implemented",
		),
	}
}

type UpdateTranslationResponder interface {
	middleware.Responder
	UpdateTranslationResponder()
}
