// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/MarcSky/freon/api/openapi/frontend/model"
)

// UserChangeProfileNoContentCode is the HTTP code returned for type UserChangeProfileNoContent
const UserChangeProfileNoContentCode int = 204

/*UserChangeProfileNoContent No content in answer

swagger:response userChangeProfileNoContent
*/
type UserChangeProfileNoContent struct {
}

// NewUserChangeProfileNoContent creates UserChangeProfileNoContent with default headers values
func NewUserChangeProfileNoContent() *UserChangeProfileNoContent {

	return &UserChangeProfileNoContent{}
}

// WriteResponse to the client
func (o *UserChangeProfileNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *UserChangeProfileNoContent) UserChangeProfileResponder() {}

/*UserChangeProfileDefault General errors using same model as used by go-swagger for validation errors.

swagger:response userChangeProfileDefault
*/
type UserChangeProfileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewUserChangeProfileDefault creates UserChangeProfileDefault with default headers values
func NewUserChangeProfileDefault(code int) *UserChangeProfileDefault {
	if code <= 0 {
		code = 500
	}

	return &UserChangeProfileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user change profile default response
func (o *UserChangeProfileDefault) WithStatusCode(code int) *UserChangeProfileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user change profile default response
func (o *UserChangeProfileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user change profile default response
func (o *UserChangeProfileDefault) WithPayload(payload *model.Error) *UserChangeProfileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user change profile default response
func (o *UserChangeProfileDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserChangeProfileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *UserChangeProfileDefault) UserChangeProfileResponder() {}

type UserChangeProfileNotImplementedResponder struct {
	middleware.Responder
}

func (*UserChangeProfileNotImplementedResponder) UserChangeProfileResponder() {}

func UserChangeProfileNotImplemented() UserChangeProfileResponder {
	return &UserChangeProfileNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.UserChangeProfile has not yet been implemented",
		),
	}
}

type UserChangeProfileResponder interface {
	middleware.Responder
	UserChangeProfileResponder()
}
