// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/freonservice/freon/internal/app"
)

// VersionHandlerFunc turns a function with the right signature into a version handler
type VersionHandlerFunc func(VersionParams, *app.UserSession) VersionResponder

// Handle executing the request and returning a response
func (fn VersionHandlerFunc) Handle(params VersionParams, principal *app.UserSession) VersionResponder {
	return fn(params, principal)
}

// VersionHandler interface for that can handle valid version params
type VersionHandler interface {
	Handle(VersionParams, *app.UserSession) VersionResponder
}

// NewVersion creates a new http.Handler for the version operation
func NewVersion(ctx *middleware.Context, handler VersionHandler) *Version {
	return &Version{Context: ctx, Handler: handler}
}

/*Version swagger:route GET /version version

get actual version of translation files ( 0 - web, 1 - ios, 2 - android) or translations (3 - get last updated date)

*/
type Version struct {
	Context *middleware.Context
	Handler VersionHandler
}

func (o *Version) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVersionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *app.UserSession
	if uprinc != nil {
		principal = uprinc.(*app.UserSession) // this is really a app.UserSession, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
